

services:
  ornstein-zernike:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: density
    volumes:
      - ./:/workspace
      - ./output_local:/workspace/output
      - volumen_lanimfe:/data_output
    working_dir: /workspace
    environment:
      - DENSITIES=${DENSITIES}
      - DIMENSION=${DIMENSION}
      - KBT=${KBT}
      - FOLDER_NAME=${FOLDER_NAME}
    entrypoint: ["bash", "./entrypoint.sh"]

volumes:
  volumen_lanimfe:
