

services:
  ornstein-zernike:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ng_STAGES
    volumes:
      - ./:/workspace
      - ./output_local:/workspace/output
      - volumen_lanimfe:/data_output
    working_dir: /workspace
    environment:
      - PHI=${PHI}
      - KBT=${KBT}
      - M=${M}
      - N_STAGES=${N_STAGES}
      - FOLDER_NAME=${FOLDER_NAME}
    entrypoint: ["bash", "./entrypoint.sh"]

volumes:
  volumen_lanimfe:
