# Usamos la imagen oficial de Julia
FROM julia:1.10

# Actualizar el sistema e instalar las dependencias necesarias
RUN apt-get update && apt-get install -y \
    bash \
    curl \
    wget \
    git \
    build-essential \
    libcurl4-openssl-dev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Crear directorio de trabajo
WORKDIR /workspace

# Clonar el repositorio del paquete
RUN git clone https://github.com/IlianPihlajamaa/OrnsteinZernike.jl

# Instalar los paquetes de Julia necesarios
RUN julia -e 'using Pkg; Pkg.add(PackageSpec(path="/workspace/OrnsteinZernike.jl")); Pkg.instantiate()'
RUN julia -e 'using Pkg; Pkg.add("JSON")'

# Crear directorio para la salida
ENV OUTPUT_DIR="/workspace/carpeta"
RUN mkdir -p $OUTPUT_DIR

# Copiar el script que se va a utilizar
COPY OZE2_HS.jl .

# Copiar el script de shell para ejecutar
COPY entrypoint.sh .

# Dar permisos de ejecución al script
RUN chmod +x entrypoint.sh

# Establecer variable de entorno
ENV PARAM=0.1

# Establecer el punto de entrada usando bash explícitamente
ENTRYPOINT ["bash", "./entrypoint.sh"]