version: '3.9'

services:
  wca_container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wca_container_custom
    volumes:
      - ./:/workspace
      - ./output_local:/workspace/output
      - volumen_WCA:/data_output
    working_dir: /workspace
    environment:
      - PHI=${PHI}
      - KBT=${KBT}
      - SIGMA=${SIGMA}
      - EPSILON=${EPSILON}
      - FOLDER_NAME=${FOLDER_NAME}
      - CLOSURE=${CLOSURE}
    entrypoint: ["bash", "./entrypoint.sh"]

volumes:
  volumen_WCA:
