services:
  scgle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dinamica_mct
    volumes:
      - ./:/workspace
      - ./output_local:/workspace/output
      - volumen_scgle:/data_output
    working_dir: /workspace
    environment:
      - PHI=${PHI}
      - FOLDER_NAME=${FOLDER_NAME}
    entrypoint: ["bash", "./entrypoint.sh"]

volumes:
  volumen_scgle:
#docker-compose down --volumes
#docker system prune -a --volumes -f
