

services:
  ornstein-zernike:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: power_law
    volumes:
      - ./:/workspace
      - ./output_local:/workspace/output
      - volumen_lanimfe:/data_output
    working_dir: /workspace
    environment:
      - EPSILON=${EPSILON}
      - SIGMA=${SIGMA}
      - N=${N}
      - PHI=${PHI}
      - KBT=${KBT}
      - FOLDER_NAME=${FOLDER_NAME}
    entrypoint: ["bash", "./entrypoint.sh"]

volumes:
  volumen_lanimfe:
