FROM julia:1.11

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    bash curl wget git build-essential libcurl4-openssl-dev ca-certificates dos2unix \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

# Clonar el repositorio
RUN git clone https://github.com/IlianPihlajamaa/OrnsteinZernike.jl

# Instalar paquetes Julia
RUN julia -e 'using Pkg; Pkg.add(PackageSpec(path="OrnsteinZernike.jl")); Pkg.instantiate()'
RUN julia -e 'using Pkg; Pkg.add("JSON"); Pkg.add("DelimitedFiles")'

# Copiar archivos de usuario
COPY power_dockerduo.jl /workspace/power_dockerduo.jl
COPY entrypoint.sh /workspace/entrypoint.sh

# Asegurar que el script tenga formato UNIX y permisos
RUN dos2unix /workspace/entrypoint.sh && chmod +x /workspace/entrypoint.sh

# Ejecutar script
ENTRYPOINT ["bash", "/workspace/entrypoint.sh"]
#windows$env:PHI="0.23"; $env:KBT="2.0"; $env:FOLDER_NAME="nuevop"; docker compose up --build --force-recreate
#macPHI=0.23 KBT=2.0 FOLDER_NAME=nuevop docker compose up --build --force-recreate
#ubuntu export PHI=0.23; export KBT=2.0; export FOLDER_NAME=nuevop; docker compose up --build --force-recreate


